In [3]:
import pandas as pd
df = pd.read_csv('Zomato Dataset.csv')
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
df.describe(include='all')

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
count,45584,45584,43730.000000,43676.000000,45584.000000,45584.000000,45584.000000,45584.000000,45584,43853,45584,44968,44983,45584.000000,45584,45584,44591.000000,45356,44384,45584.000000
unique,45584,1320,NaN,NaN,NaN,NaN,NaN,NaN,44,176,193,6,4,NaN,4,4,NaN,2,3,NaN
top,0xcdcd,JAPRES11DEL02,NaN,NaN,NaN,NaN,NaN,NaN,15-03-2022,21:55,21:30,Fog,Low,NaN,Snack,motorcycle,NaN,No,Metropolitian,NaN
freq,1,67,NaN,NaN,NaN,NaN,NaN,NaN,1192,461,495,7653,15476,NaN,11530,26429,NaN,44460,34087,NaN
mean,NaN,NaN,29.566911,4.633774,17.017948,70.229684,17.465480,70.844161,NaN,NaN,NaN,NaN,NaN,1.023385,NaN,NaN,0.744635,NaN,NaN,26.293963
std,NaN,NaN,5.815064,0.334744,8.185674,22.885575,7.335562,21.120578,NaN,NaN,NaN,NaN,NaN,0.839055,NaN,NaN,0.572510,NaN,NaN,9.384298
min,NaN,NaN,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,10.000000
25%,NaN,NaN,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,19.000000
50%,NaN,NaN,30.000000,4.700000,18.551440,75.897963,18.633934,76.002574,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,NaN,NaN,26.000000
75%,NaN,NaN,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,1.000000,NaN,NaN,32.000000
max,NaN,NaN,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,3.000000,NaN,NaN,54.000000

In [5]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [6]:
# Numerical columns → median
num_cols = ['Delivery_person_Age', 'Delivery_person_Ratings', 'multiple_deliveries']
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Categorical columns → mode
cat_cols = ['Weather_conditions', 'Road_traffic_density', 'Festival', 'City']
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

# Time column → forward fill
df['Time_Orderd'] = df['Time_Orderd'].fillna(method='ffill')

C:\Users\Iman bohare\AppData\Local\Temp\ipykernel_25880\2217710037.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Time_Orderd'] = df['Time_Orderd'].fillna(method='ffill')

In [7]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken (min)               0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(',','_')
df.columns

Index(['id', 'delivery_person_id', 'delivery_person_age',
       'delivery_person_ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_location_latitude',
       'delivery_location_longitude', 'order_date', 'time_orderd',
       'time_order_picked', 'weather_conditions', 'road_traffic_density',
       'vehicle_condition', 'type_of_order', 'type_of_vehicle',
       'multiple_deliveries', 'festival', 'city', 'time_taken (min)'],
      dtype='object')

The columns readable and consistent

In [9]:
df = df.rename(columns={ 'time_taken (min)':'total_minutes'})
df.columns

Index(['id', 'delivery_person_id', 'delivery_person_age',
       'delivery_person_ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_location_latitude',
       'delivery_location_longitude', 'order_date', 'time_orderd',
       'time_order_picked', 'weather_conditions', 'road_traffic_density',
       'vehicle_condition', 'type_of_order', 'type_of_vehicle',
       'multiple_deliveries', 'festival', 'city', 'total_minutes'],
      dtype='object')

In [10]:
labels = ['young','adult','middle_aged','senior']

df['age_level'] = pd.qcut(df['delivery_person_age'], q=4, labels=labels)

df[['age_level','delivery_person_age']].head(10)

     age_level  delivery_person_age
0       senior                 36.0
1        young                 21.0
2        young                 23.0
3  middle_aged                 34.0
4        young                 24.0
5        adult                 29.0
6       senior                 35.0
7  middle_aged                 33.0
8  middle_aged                 34.0
9        young                 21.0

The delivery person

In [11]:
print((df['age_level'] == 'young').sum())

12991

In [12]:
pip install pandas sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\iman bohare\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.9.11)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas
import sqlalchemy
import psycopg2

print("All modules working ✅")

All modules working ✅

In [14]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "Netbeans" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "Zomato"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "zomatotable"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'zomatotable' in database 'Zomato'.